# Generated by Django 3.0.3 on 2020-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200520_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
